"""Add system_config table

Revision ID: bb633fd56b8a
Revises: 545436b3da24
Create Date: 2026-01-25 16:12:56.621838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb633fd56b8a'
down_revision: Union[str, Sequence[str], None] = '545436b3da24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_master_trading_symbol'), table_name='instrument_master')
    op.drop_table('instrument_master')
    op.drop_index(op.f('ix_order_ledger_exchange_id'), table_name='order_ledger')
    op.drop_index(op.f('ix_order_ledger_status'), table_name='order_ledger')
    op.drop_table('order_ledger')
    op.drop_table('market_ticks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_key_enc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_secret_enc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mpin_enc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('market_ticks',
    sa.Column('tick_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ltp', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tick_time', 'token', name=op.f('market_ticks_pkey'))
    )
    op.create_table('order_ledger',
    sa.Column('internal_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('trigger_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strategy_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['token'], ['instrument_master.instrument_token'], name=op.f('order_ledger_token_fkey')),
    sa.PrimaryKeyConstraint('internal_id', name=op.f('order_ledger_pkey'))
    )
    op.create_index(op.f('ix_order_ledger_status'), 'order_ledger', ['status'], unique=False)
    op.create_index(op.f('ix_order_ledger_exchange_id'), 'order_ledger', ['exchange_id'], unique=False)
    op.create_table('instrument_master',
    sa.Column('instrument_token', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exchange_token', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trading_symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lot_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tick_size', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('freeze_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('segment', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('instrument_token', name=op.f('instrument_master_pkey'))
    )
    op.create_index(op.f('ix_instrument_master_trading_symbol'), 'instrument_master', ['trading_symbol'], unique=False)
    # ### end Alembic commands ###
